// Generated by Wrangler
interface Env {
	GS_CONFIG: KVNamespace;
	ENVIRONMENT: "production";
	AIPROXYSIGNING_KEY: string;
	DB: D1Database;
	AI: any;
	VERSION: { id: string; tag: string };
	AGENT: Fetcher;
}
