name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        id: init
        run: terraform -chdir=terraform init

      - name: Terraform Plan
        id: plan
        run: |
          terraform -chdir=terraform plan -out=tfplan \
            -var="cloudflare_account_id=${{ secrets.CLOUDFLARE_ACCOUNT_ID }}" \
            -var="github_owner=${{ github.repository_owner }}" \
            -var="cloudflare_api_token=${{ secrets.CLOUDFLARE_API_TOKEN }}"

      - name: Terraform Apply
        id: apply
        run: terraform -chdir=terraform apply -auto-approve tfplan
